[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'haxibami/urara.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
        \ 'colorscheme': 'urara',
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ],
        \             [ 'readonly', 'filename', 'modified' ] ]
        \ },
        \ }
'''

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

[[plugins]]
repo = 'lilydjwg/fcitx.vim'
rev = 'fcitx5'
hook_add = '''
  let g:fcitx5_remote = "/usr/bin/fcitx5-remote"
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  " g]で前の変更箇所へ移動する
  nnoremap g[ :GitGutterPrevHunk<CR>
  " g[で次の変更箇所へ移動する
  nnoremap g] :GitGutterNextHunk<CR>
  " ghでdiffをハイライトする
  nnoremap gh :GitGutterLineHighlightsToggle<CR>
  " gpでカーソル行のdiffを表示する
  nnoremap gp :GitGutterPreviewHunk<CR>
  " 記号の色を変更する
  highlight GitGutterAdd ctermfg=green
  highlight GitGutterChange ctermfg=blue
  highlight GitGutterDelete ctermfg=red
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
  fun! FzfOmniFiles()
    let is_git = system('git status')
    if v:shell_error
      :Files
    else
      :GFiles
    endif
  endfun
  nnoremap <C-p> :call FzfOmniFiles()<CR>
'''

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = ':TSUpdate'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
hook_add = '''
  lua require('colorizer').setup()
'''
