padding-x = 25
theme = "claymore"

[renderer]
performance = "High"

[window]
background-opacity = 1
blur = true

[fonts]
size = 30
family = "FirgeNerd Console"

# [bindings]
# keys = [
#   #{ key = "t", with = "control", action = "None" },
#   #{ key = "n", with = "control", action = "None" },
# ]
# # Bytes[27, 91, 53, 126] is equivalent to "\x1b[5~"
# # { key = "home", with = "super | shift", bytes = [27, 91, 53, 126] },
