#!/bin/sh

XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=sway
XDG_CURRENT_SESSION=sway
LIBSEAT_BACKEND=logind
QT_QPA_PLATFORM="wayland;xcb"
GDK_DPI_SCALE=1.5
QT_SCALE_FACTOR=1.5
QT_AUTO_SCREEN_SCALE_FACTOR=0
MOZ_ENABLE_WAYLAND=1
WINIT_UNIX_BACKEND=x11
_JAVA_AWT_WM_NONREPARENTING=1
#STUDIO_JDK=/usr/lib/jvm/java-11-openjdk
#WLR_RENDERER=vulkan

export XDG_SESSION_TYPE XDG_CURRENT_DESKTOP XDG_CURRENT_SESSION LIBSEAT_BACKEND QT_QPA_PLATFORM GDK_DPI_SCALE QT_SCALE_FACTOR MOZ_ENABLE_WAYLAND WINIT_UNIX_BACKEND QT_AUTO_SCREEN_SCALE_FACTOR _JAVA_AWT_WM_NONREPARENTING;

#eval $(/usr/bin/gnome-keyring-daemon --start);
#export SSH_AUTH_SOCK;
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1;

#sleep 1;
exec sway
