#!/bin/sh

XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=sway
XDG_CURRENT_SESSION=sway
DESKTOP_SESSION=sway
QT_QPA_PLATFORM="wayland;xcb"
#GDK_DPI_SCALE=1.5
GDK_SCALE=2
#QT_SCALE_FACTOR=1
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_QPA_PLATFORMTHEME=gnome
QT_STYLE_OVERRIDE=kvantum
QT_FONT_DPI=132
MOZ_ENABLE_WAYLAND=1
_JAVA_AWT_WM_NONREPARENTING=1
#STUDIO_JDK=/usr/lib/jvm/java-11-openjdk
#WLR_RENDERER=vulkan
SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/gcr/ssh"

export XDG_SESSION_TYPE XDG_CURRENT_DESKTOP XDG_CURRENT_SESSION DESKTOP_SESSION QT_QPA_PLATFORM GDK_DPI_SCALE QT_SCALE_FACTOR QT_AUTO_SCREEN_SCALE_FACTOR QT_QPA_PLATFORMTHEME QT_STYLE_OVERRIDE QT_FONT_DPI MOZ_ENABLE_WAYLAND _JAVA_AWT_WM_NONREPARENTING WLR_RENDERER SSH_AUTH_SOCK;

systemd-cat --identifier=sway sway $@
