#!/bin/sh

XDG_SESSION_TYPE=wayland
XDG_CURRENT_DESKTOP=sway
XDG_CURRENT_SESSION=sway
QT_QPA_PLATFORM="wayland;xcb"
#GDK_DPI_SCALE=1.5
GDK_SCALE=2
QT_SCALE_FACTOR=1.5
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_QPA_PLATFORMTHEME=qt5ct
QT_STYLE_OVERRIDE=kvantum
MOZ_ENABLE_WAYLAND=1
WINIT_UNIX_BACKEND=x11
_JAVA_AWT_WM_NONREPARENTING=1
#STUDIO_JDK=/usr/lib/jvm/java-11-openjdk
#WLR_RENDERER=vulkan

export XDG_SESSION_TYPE XDG_CURRENT_DESKTOP XDG_CURRENT_SESSION QT_QPA_PLATFORM GDK_DPI_SCALE QT_SCALE_FACTOR QT_AUTO_SCREEN_SCALE_FACTOR QT_QPA_PLATFORMTHEME QT_STYLE_OVERRIDE MOZ_ENABLE_WAYLAND WINIT_UNIX_BACKEND _JAVA_AWT_WM_NONREPARENTING;

if [ -n "$DESKTOP_SESSION" ]; then
  eval $(gnome-keyring-daemon --start)
  export SSH_AUTH_SOCK
fi

dbus-update-activation-environment --systemd SSH_AUTH_SOCK

exec sway
