[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

[[plugins]]
repo = 'lilydjwg/fcitx.vim'
rev = 'fcitx5'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
