add_newline = true

scan_timeout = 10

format = """
$directory$git_branch$git_status$hostname
$character(white)"""

[character]
success_symbol = "[>](#9abf86)"
error_symbol = "[>](#d9989c)"
vicmd_symbol = "[>](#d9c77e)"

[directory]
truncation_length = 5
format = " [$read_only]($read_only_style)[$path](bold underline #a6b4de) "

[hostname]
ssh_only = false
format = "on [$hostname](bold #86bfb6) [$ssh_symbol](white)"

[git_branch]
style = "bold green"
format = "[$branch $symbol](bold green)"
